### ISSUE TITLE
Notification Badge Should not be Shown When Chat is Muted

### ISSUE THREAD

**Issue by benmarten** [bcalik/Whatsapp-Desktop#10]
Just noticed, that when a group chat is muted I still get notifications!
The red badge still appears... Is that something that could be fixed by the client?
<img width="401" alt="screen shot 2015-08-21 at 20 00 37" src="https://cloud.githubusercontent.com/assets/5960238/9415423/a29c17cc-483f-11e5-8d37-8ecb5f26958e.png">

**Comment by shulhi** [comment]
@bcalik Is there a way to get the content of the `browser-window`? I thought of traversing each chat list and build the notifications from there. I looked at Electron's documentation but couldn't find a way to get the content from the `browser-window`.

**Comment by bcalik** [comment]
@shulhi That is what I was thinking at first, I will do it when I have a free time.
I'm not sure how but you can execute javascript using [WebContents.executeJavascript](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#webcontentsexecutejavascriptcode-usergesture).

**Comment by shulhi** [comment]
@bcalik Actually, I am working on this. I thought of using [cheerio](https://www.npmjs.com/package/cheerio) to parse the DOM and find all the nodes, update the unread messages and pass that to the main process using IPC. However, this does not work since whenever I enabled `node-integration` to `true`, I received these errors:

```
8627:0827/152603:INFO:CONSOLE(29)] "Uncaught TypeError: Cannot read property 'configurable' of undefined", source: https://web.whatsapp.com/lib/bluebird-2.9.24.min.js (29)
[8627:0827/152603:INFO:CONSOLE(0)] "Application Cache Progress event (29 of 29) ", source: https://web.whatsapp.com/ (0)
[8627:0827/152603:INFO:CONSOLE(0)] "Application Cache Cached event", source: https://web.whatsapp.com/ (0)
[8627:0827/152604:INFO:CONSOLE(2)] "Uncaught Error: Missing Dependencies: ", source: https://web.whatsapp.com/app_19053ba64f7dfa719aab.js (2)
[8627:0827/152605:INFO:CONSOLE(0)] "XMLHttpRequest cannot load https://web-crashlog.whatsapp.net/upload.php. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://web.whatsapp.com' is therefore not allowed access. The response had HTTP status code 403.", source: https://web.whatsapp.com/ (0)
```

Any idea why this is happening? If not, I would have to resort to purely using Javascript to do the DOM traversal and update the title accordingly from there.

You can view my work-in-progress here https://github.com/shulhi/Whatsapp-Desktop/blob/feature/better-notification/app/app.js

**Comment by shulhi** [comment]
I just noticed that muted conversations do not show pop up notifications on OSX, but non-muted conversations do. 

Can we capture these 'events' before it goes to show pop up?

**Comment by mathsalmi** [comment]
I gave a quick look at the pull request #18 and once it's accepted I think we can solve this problem easily. 

I thought about changing the hack that updates the badge: instead of updating it when the title changes, we could add a MutationObserver on the chat tabs on the sidebar so whenever it was detected some change there, we'd see if there is a badge and there is not the silent icon. If both are true, then we can update the badge icon and bounce it on OSX.

Later I'll do some experiments and see what I get with it.

(PS: perhaps we don't necessarily need to wait for the merge but it'd be good since it improves a lot of things).

**Comment by bcalik** [comment]
@mathsalmi Ok I merged, but I did not check if it has issues.

**Comment by mathsalmi** [comment]
@bcalik I should check it better later but for what I've seen it doesn't break anything. There are just some small things on the Settings window that don't work properly on OSX but they are minor.

Later, I'll play with the idea I gave and then I'll get back to you =)

**Comment by mathsalmi** [comment]
So, back to work. I've been testing the idea I gave above but I needed to make some big changes in order to get things working as expected. This caused the Settings window (introduced on the merge of the pull-request #18) to stop working.

I'll describe all changes when I make a pull-request but for now I just wanted to bring the good news: it worked. (in a very ugly hacky way but it did work).

**Comment by ffuen7es** [comment]
@mathsalmi , @benmarten have you guys/do you know of anyone who has been working on this for iPhone badge notifications. I believe it is the same problem: I would like my badge count on top of the WApp icon to reflect new messages from unmuted contacts/groups only, and right now unmuted messages are included in there.

many thanks in advance

**Comment by matthewgertner** [comment]
@mathsalmi @benmarten Can I ask what is the status of this issue? I see it was closed over a year ago, but like @ffuen7es I am still experiencing precisely the issue reported by the OP.

**Comment by mathsalmi** [comment]
@matthewgertner Sorry, I'm no longer using it. I've switched to Franz 2 years ago.

**Comment by matthewgertner** [comment]
Ah OK... guess I should have mentioned @bcalik.

**Comment by bcalik** [comment]
@matthewgertner This is no longer maintained. See the readme.
https://github.com/bcalik/Whatsapp-Desktop
